services:
  postgres:
    image: postgres:16-alpine
    command: "-c max_prepared_transactions=10"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql


volumes:
  postgres-data: ~