entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: leresolver
        domains:
          - main: botenza.org
            sans:
              - traefik.botenza.org
              - roulette.botenza.org

log:
  level: DEBUG
  filePath: "/tmp/traefik.log"

providers:
  docker: {}
  file:
    filename: /etc/traefik/http.yml

api:
  insecure: false


certificatesResolvers:
  leresolver:
    acme:
      email: sashaaro@gmail.com
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web