name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Run init.sql
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d test_db -f ./account/init.sql
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check code formatting with rustfmt
        run: cargo fmt --all -- --check

      - name: Wait for PostgreSQL
        run: sleep 5  # Даём время PostgreSQL запуститься

      - name: Run account tests
        run: |
          cargo test --package account --bin account
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test_db"